CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE "users" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" varchar,
  "email" varchar,
  "password_hash" varchar,
  "status_id" integer default 1,
  "refresh_token" text,
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_by" uuid,
  "updated_by" uuid
);

CREATE TABLE "master_status" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "is_active" boolean default true
);

CREATE TABLE "licenses" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" varchar,
  "monthly_price" decimal,
  "status_id" integer DEFAULT 1,
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_by" uuid,
  "updated_by" uuid
);

CREATE TABLE "orders" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid,
  "invoice_no" varchar,
  "invoice_date" timestamp,
  "total_amount" decimal(10, 2),
  "payment_status_id" int DEFAULT 1,
  "status_id" integer DEFAULT 1,
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_by" uuid,
  "updated_by" uuid
);

CREATE TABLE "order_items" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid,
  "order_id" uuid,
  "license_id" uuid,
  "quantity" int NOT NULL,
  "amount_per_qty" decimal(10, 2),
  "amount_total_qty" decimal(10, 2),
  "purchase_date" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "start_date" DATE NOT NULL,
  "expiry_date" DATE NOT NULL,
  "status_id" integer DEFAULT 1,
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_by" uuid,
  "updated_by" uuid
);

CREATE TABLE "payments" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "order_id" uuid,
  "amount" decimal(10, 2),
  "payment_method" varchar,
  "payment_status_id" int DEFAULT 1,
  "paid_at" timestamp,
  "status_id" integer DEFAULT 1,
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "created_by" uuid,
  "updated_by" uuid
);

CREATE TABLE "master_payment_status" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "status_id" int DEFAULT 1
);

ALTER TABLE "users" ADD FOREIGN KEY ("status_id") REFERENCES "master_status" ("id");

ALTER TABLE "licenses" ADD FOREIGN KEY ("status_id") REFERENCES "master_status" ("id");

ALTER TABLE "licenses" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "licenses" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("payment_status_id") REFERENCES "master_payment_status" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("status_id") REFERENCES "master_status" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("license_id") REFERENCES "licenses" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("status_id") REFERENCES "master_status" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("payment_status_id") REFERENCES "master_payment_status" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("status_id") REFERENCES "master_status" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("updated_by") REFERENCES "users" ("id");

ALTER TABLE "master_payment_status" ADD FOREIGN KEY ("status_id") REFERENCES "master_status" ("id");
