post /api/v1/orders/ HTTP/1.1
Host: localhost:3000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNTNmZjE5NDgtNzkyNy00ZjAwLTlkZDItYTZmZTE5MGNlMjkyIiwiaWF0IjoxNzcwNTE3NTQ5LCJleHAiOjE3NzA2MDM5NDl9.k1hKYTlO5YZklcvO-QuAKGOJ9ACUoKL_ntX4KYv0nfg

{
    "total_amount": 80,
    "order_items": [
        {
            "license_id": "53ff1948-7927-4f00-9dd2-a6fe190ce291",
            "quantity": 2,
            "amount_per_unit": 10
        },
          {
            "license_id": "53ff1948-7927-4f00-9dd2-a6fe190ce293",
            "quantity": 3,
            "amount_per_unit": 20
        }
    ]
}